// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
namespace frp {
class AddConnReq;
struct AddConnReqDefaultTypeInternal;
extern AddConnReqDefaultTypeInternal _AddConnReq_default_instance_;
class AddConnRsp;
struct AddConnRspDefaultTypeInternal;
extern AddConnRspDefaultTypeInternal _AddConnRsp_default_instance_;
class Config;
struct ConfigDefaultTypeInternal;
extern ConfigDefaultTypeInternal _Config_default_instance_;
class LocalConf;
struct LocalConfDefaultTypeInternal;
extern LocalConfDefaultTypeInternal _LocalConf_default_instance_;
class LoginReq;
struct LoginReqDefaultTypeInternal;
extern LoginReqDefaultTypeInternal _LoginReq_default_instance_;
class LoginRsp;
struct LoginRspDefaultTypeInternal;
extern LoginRspDefaultTypeInternal _LoginRsp_default_instance_;
class Msg;
struct MsgDefaultTypeInternal;
extern MsgDefaultTypeInternal _Msg_default_instance_;
class ServerConf;
struct ServerConfDefaultTypeInternal;
extern ServerConfDefaultTypeInternal _ServerConf_default_instance_;
}  // namespace frp
PROTOBUF_NAMESPACE_OPEN
template<> ::frp::AddConnReq* Arena::CreateMaybeMessage<::frp::AddConnReq>(Arena*);
template<> ::frp::AddConnRsp* Arena::CreateMaybeMessage<::frp::AddConnRsp>(Arena*);
template<> ::frp::Config* Arena::CreateMaybeMessage<::frp::Config>(Arena*);
template<> ::frp::LocalConf* Arena::CreateMaybeMessage<::frp::LocalConf>(Arena*);
template<> ::frp::LoginReq* Arena::CreateMaybeMessage<::frp::LoginReq>(Arena*);
template<> ::frp::LoginRsp* Arena::CreateMaybeMessage<::frp::LoginRsp>(Arena*);
template<> ::frp::Msg* Arena::CreateMaybeMessage<::frp::Msg>(Arena*);
template<> ::frp::ServerConf* Arena::CreateMaybeMessage<::frp::ServerConf>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace frp {

enum MsgType : int {
  MSGTYPE_UNKNOWN = 0,
  MSGTYPE_LOGIN_REQ = 1,
  MSGTYPE_LOGIN_RSP = 2,
  MSGTYPE_ADD_CONN_REQ = 3,
  MSGTYPE_ADD_CONN_RSP = 4,
  MsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MsgType_IsValid(int value);
constexpr MsgType MsgType_MIN = MSGTYPE_UNKNOWN;
constexpr MsgType MsgType_MAX = MSGTYPE_ADD_CONN_RSP;
constexpr int MsgType_ARRAYSIZE = MsgType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MsgType_descriptor();
template<typename T>
inline const std::string& MsgType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MsgType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MsgType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MsgType_descriptor(), enum_t_value);
}
inline bool MsgType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MsgType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MsgType>(
    MsgType_descriptor(), name, value);
}
enum Protocol : int {
  TCP = 0,
  Protocol_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Protocol_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Protocol_IsValid(int value);
constexpr Protocol Protocol_MIN = TCP;
constexpr Protocol Protocol_MAX = TCP;
constexpr int Protocol_ARRAYSIZE = Protocol_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Protocol_descriptor();
template<typename T>
inline const std::string& Protocol_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Protocol>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Protocol_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Protocol_descriptor(), enum_t_value);
}
inline bool Protocol_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Protocol* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Protocol>(
    Protocol_descriptor(), name, value);
}
// ===================================================================

class Msg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:frp.Msg) */ {
 public:
  inline Msg() : Msg(nullptr) {}
  ~Msg() override;
  explicit constexpr Msg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Msg(const Msg& from);
  Msg(Msg&& from) noexcept
    : Msg() {
    *this = ::std::move(from);
  }

  inline Msg& operator=(const Msg& from) {
    CopyFrom(from);
    return *this;
  }
  inline Msg& operator=(Msg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Msg& default_instance() {
    return *internal_default_instance();
  }
  static inline const Msg* internal_default_instance() {
    return reinterpret_cast<const Msg*>(
               &_Msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Msg& a, Msg& b) {
    a.Swap(&b);
  }
  inline void Swap(Msg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Msg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Msg* New() const final {
    return new Msg();
  }

  Msg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Msg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Msg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Msg& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Msg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "frp.Msg";
  }
  protected:
  explicit Msg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLoginReqFieldNumber = 2,
    kLoginRspFieldNumber = 3,
    kAddConnReqFieldNumber = 4,
    kAddConnRspFieldNumber = 5,
    kTypeFieldNumber = 1,
  };
  // .frp.LoginReq loginReq = 2;
  bool has_loginreq() const;
  private:
  bool _internal_has_loginreq() const;
  public:
  void clear_loginreq();
  const ::frp::LoginReq& loginreq() const;
  PROTOBUF_MUST_USE_RESULT ::frp::LoginReq* release_loginreq();
  ::frp::LoginReq* mutable_loginreq();
  void set_allocated_loginreq(::frp::LoginReq* loginreq);
  private:
  const ::frp::LoginReq& _internal_loginreq() const;
  ::frp::LoginReq* _internal_mutable_loginreq();
  public:
  void unsafe_arena_set_allocated_loginreq(
      ::frp::LoginReq* loginreq);
  ::frp::LoginReq* unsafe_arena_release_loginreq();

  // .frp.LoginRsp loginRsp = 3;
  bool has_loginrsp() const;
  private:
  bool _internal_has_loginrsp() const;
  public:
  void clear_loginrsp();
  const ::frp::LoginRsp& loginrsp() const;
  PROTOBUF_MUST_USE_RESULT ::frp::LoginRsp* release_loginrsp();
  ::frp::LoginRsp* mutable_loginrsp();
  void set_allocated_loginrsp(::frp::LoginRsp* loginrsp);
  private:
  const ::frp::LoginRsp& _internal_loginrsp() const;
  ::frp::LoginRsp* _internal_mutable_loginrsp();
  public:
  void unsafe_arena_set_allocated_loginrsp(
      ::frp::LoginRsp* loginrsp);
  ::frp::LoginRsp* unsafe_arena_release_loginrsp();

  // .frp.AddConnReq addConnReq = 4;
  bool has_addconnreq() const;
  private:
  bool _internal_has_addconnreq() const;
  public:
  void clear_addconnreq();
  const ::frp::AddConnReq& addconnreq() const;
  PROTOBUF_MUST_USE_RESULT ::frp::AddConnReq* release_addconnreq();
  ::frp::AddConnReq* mutable_addconnreq();
  void set_allocated_addconnreq(::frp::AddConnReq* addconnreq);
  private:
  const ::frp::AddConnReq& _internal_addconnreq() const;
  ::frp::AddConnReq* _internal_mutable_addconnreq();
  public:
  void unsafe_arena_set_allocated_addconnreq(
      ::frp::AddConnReq* addconnreq);
  ::frp::AddConnReq* unsafe_arena_release_addconnreq();

  // .frp.AddConnRsp addConnRsp = 5;
  bool has_addconnrsp() const;
  private:
  bool _internal_has_addconnrsp() const;
  public:
  void clear_addconnrsp();
  const ::frp::AddConnRsp& addconnrsp() const;
  PROTOBUF_MUST_USE_RESULT ::frp::AddConnRsp* release_addconnrsp();
  ::frp::AddConnRsp* mutable_addconnrsp();
  void set_allocated_addconnrsp(::frp::AddConnRsp* addconnrsp);
  private:
  const ::frp::AddConnRsp& _internal_addconnrsp() const;
  ::frp::AddConnRsp* _internal_mutable_addconnrsp();
  public:
  void unsafe_arena_set_allocated_addconnrsp(
      ::frp::AddConnRsp* addconnrsp);
  ::frp::AddConnRsp* unsafe_arena_release_addconnrsp();

  // .frp.MsgType type = 1;
  void clear_type();
  ::frp::MsgType type() const;
  void set_type(::frp::MsgType value);
  private:
  ::frp::MsgType _internal_type() const;
  void _internal_set_type(::frp::MsgType value);
  public:

  // @@protoc_insertion_point(class_scope:frp.Msg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::frp::LoginReq* loginreq_;
  ::frp::LoginRsp* loginrsp_;
  ::frp::AddConnReq* addconnreq_;
  ::frp::AddConnRsp* addconnrsp_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class LoginReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:frp.LoginReq) */ {
 public:
  inline LoginReq() : LoginReq(nullptr) {}
  ~LoginReq() override;
  explicit constexpr LoginReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginReq(const LoginReq& from);
  LoginReq(LoginReq&& from) noexcept
    : LoginReq() {
    *this = ::std::move(from);
  }

  inline LoginReq& operator=(const LoginReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginReq& operator=(LoginReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginReq* internal_default_instance() {
    return reinterpret_cast<const LoginReq*>(
               &_LoginReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LoginReq& a, LoginReq& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginReq* New() const final {
    return new LoginReq();
  }

  LoginReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LoginReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const LoginReq& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "frp.LoginReq";
  }
  protected:
  explicit LoginReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLocalConfFieldNumber = 1,
  };
  // .frp.LocalConf localConf = 1;
  bool has_localconf() const;
  private:
  bool _internal_has_localconf() const;
  public:
  void clear_localconf();
  const ::frp::LocalConf& localconf() const;
  PROTOBUF_MUST_USE_RESULT ::frp::LocalConf* release_localconf();
  ::frp::LocalConf* mutable_localconf();
  void set_allocated_localconf(::frp::LocalConf* localconf);
  private:
  const ::frp::LocalConf& _internal_localconf() const;
  ::frp::LocalConf* _internal_mutable_localconf();
  public:
  void unsafe_arena_set_allocated_localconf(
      ::frp::LocalConf* localconf);
  ::frp::LocalConf* unsafe_arena_release_localconf();

  // @@protoc_insertion_point(class_scope:frp.LoginReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::frp::LocalConf* localconf_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class LoginRsp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:frp.LoginRsp) */ {
 public:
  inline LoginRsp() : LoginRsp(nullptr) {}
  ~LoginRsp() override;
  explicit constexpr LoginRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginRsp(const LoginRsp& from);
  LoginRsp(LoginRsp&& from) noexcept
    : LoginRsp() {
    *this = ::std::move(from);
  }

  inline LoginRsp& operator=(const LoginRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginRsp& operator=(LoginRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginRsp* internal_default_instance() {
    return reinterpret_cast<const LoginRsp*>(
               &_LoginRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(LoginRsp& a, LoginRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginRsp* New() const final {
    return new LoginRsp();
  }

  LoginRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LoginRsp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const LoginRsp& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "frp.LoginRsp";
  }
  protected:
  explicit LoginRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrMsgFieldNumber = 2,
    kClientIdFieldNumber = 3,
    kRetCodeFieldNumber = 1,
  };
  // string err_msg = 2;
  void clear_err_msg();
  const std::string& err_msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_err_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_err_msg();
  PROTOBUF_MUST_USE_RESULT std::string* release_err_msg();
  void set_allocated_err_msg(std::string* err_msg);
  private:
  const std::string& _internal_err_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_err_msg(const std::string& value);
  std::string* _internal_mutable_err_msg();
  public:

  // string client_id = 3;
  void clear_client_id();
  const std::string& client_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_client_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_client_id();
  PROTOBUF_MUST_USE_RESULT std::string* release_client_id();
  void set_allocated_client_id(std::string* client_id);
  private:
  const std::string& _internal_client_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_id(const std::string& value);
  std::string* _internal_mutable_client_id();
  public:

  // int32 ret_code = 1;
  void clear_ret_code();
  int32_t ret_code() const;
  void set_ret_code(int32_t value);
  private:
  int32_t _internal_ret_code() const;
  void _internal_set_ret_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:frp.LoginRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr err_msg_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr client_id_;
  int32_t ret_code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class AddConnReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:frp.AddConnReq) */ {
 public:
  inline AddConnReq() : AddConnReq(nullptr) {}
  ~AddConnReq() override;
  explicit constexpr AddConnReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddConnReq(const AddConnReq& from);
  AddConnReq(AddConnReq&& from) noexcept
    : AddConnReq() {
    *this = ::std::move(from);
  }

  inline AddConnReq& operator=(const AddConnReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddConnReq& operator=(AddConnReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddConnReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddConnReq* internal_default_instance() {
    return reinterpret_cast<const AddConnReq*>(
               &_AddConnReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(AddConnReq& a, AddConnReq& b) {
    a.Swap(&b);
  }
  inline void Swap(AddConnReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddConnReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AddConnReq* New() const final {
    return new AddConnReq();
  }

  AddConnReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AddConnReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddConnReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const AddConnReq& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddConnReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "frp.AddConnReq";
  }
  protected:
  explicit AddConnReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConnIdFieldNumber = 1,
  };
  // string conn_id = 1;
  void clear_conn_id();
  const std::string& conn_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_conn_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_conn_id();
  PROTOBUF_MUST_USE_RESULT std::string* release_conn_id();
  void set_allocated_conn_id(std::string* conn_id);
  private:
  const std::string& _internal_conn_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_conn_id(const std::string& value);
  std::string* _internal_mutable_conn_id();
  public:

  // @@protoc_insertion_point(class_scope:frp.AddConnReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr conn_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class AddConnRsp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:frp.AddConnRsp) */ {
 public:
  inline AddConnRsp() : AddConnRsp(nullptr) {}
  ~AddConnRsp() override;
  explicit constexpr AddConnRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddConnRsp(const AddConnRsp& from);
  AddConnRsp(AddConnRsp&& from) noexcept
    : AddConnRsp() {
    *this = ::std::move(from);
  }

  inline AddConnRsp& operator=(const AddConnRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddConnRsp& operator=(AddConnRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddConnRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddConnRsp* internal_default_instance() {
    return reinterpret_cast<const AddConnRsp*>(
               &_AddConnRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(AddConnRsp& a, AddConnRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(AddConnRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddConnRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AddConnRsp* New() const final {
    return new AddConnRsp();
  }

  AddConnRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AddConnRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddConnRsp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const AddConnRsp& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddConnRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "frp.AddConnRsp";
  }
  protected:
  explicit AddConnRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrMsgFieldNumber = 2,
    kConnIdFieldNumber = 3,
    kRetCodeFieldNumber = 1,
  };
  // string err_msg = 2;
  void clear_err_msg();
  const std::string& err_msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_err_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_err_msg();
  PROTOBUF_MUST_USE_RESULT std::string* release_err_msg();
  void set_allocated_err_msg(std::string* err_msg);
  private:
  const std::string& _internal_err_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_err_msg(const std::string& value);
  std::string* _internal_mutable_err_msg();
  public:

  // string conn_id = 3;
  void clear_conn_id();
  const std::string& conn_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_conn_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_conn_id();
  PROTOBUF_MUST_USE_RESULT std::string* release_conn_id();
  void set_allocated_conn_id(std::string* conn_id);
  private:
  const std::string& _internal_conn_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_conn_id(const std::string& value);
  std::string* _internal_mutable_conn_id();
  public:

  // int32 ret_code = 1;
  void clear_ret_code();
  int32_t ret_code() const;
  void set_ret_code(int32_t value);
  private:
  int32_t _internal_ret_code() const;
  void _internal_set_ret_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:frp.AddConnRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr err_msg_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr conn_id_;
  int32_t ret_code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class Config final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:frp.Config) */ {
 public:
  inline Config() : Config(nullptr) {}
  ~Config() override;
  explicit constexpr Config(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Config(const Config& from);
  Config(Config&& from) noexcept
    : Config() {
    *this = ::std::move(from);
  }

  inline Config& operator=(const Config& from) {
    CopyFrom(from);
    return *this;
  }
  inline Config& operator=(Config&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Config& default_instance() {
    return *internal_default_instance();
  }
  static inline const Config* internal_default_instance() {
    return reinterpret_cast<const Config*>(
               &_Config_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Config& a, Config& b) {
    a.Swap(&b);
  }
  inline void Swap(Config* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Config* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Config* New() const final {
    return new Config();
  }

  Config* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Config>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Config& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Config& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Config* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "frp.Config";
  }
  protected:
  explicit Config(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLocalConfsFieldNumber = 2,
    kServerConfFieldNumber = 1,
  };
  // repeated .frp.LocalConf localConfs = 2;
  int localconfs_size() const;
  private:
  int _internal_localconfs_size() const;
  public:
  void clear_localconfs();
  ::frp::LocalConf* mutable_localconfs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frp::LocalConf >*
      mutable_localconfs();
  private:
  const ::frp::LocalConf& _internal_localconfs(int index) const;
  ::frp::LocalConf* _internal_add_localconfs();
  public:
  const ::frp::LocalConf& localconfs(int index) const;
  ::frp::LocalConf* add_localconfs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frp::LocalConf >&
      localconfs() const;

  // .frp.ServerConf serverConf = 1;
  bool has_serverconf() const;
  private:
  bool _internal_has_serverconf() const;
  public:
  void clear_serverconf();
  const ::frp::ServerConf& serverconf() const;
  PROTOBUF_MUST_USE_RESULT ::frp::ServerConf* release_serverconf();
  ::frp::ServerConf* mutable_serverconf();
  void set_allocated_serverconf(::frp::ServerConf* serverconf);
  private:
  const ::frp::ServerConf& _internal_serverconf() const;
  ::frp::ServerConf* _internal_mutable_serverconf();
  public:
  void unsafe_arena_set_allocated_serverconf(
      ::frp::ServerConf* serverconf);
  ::frp::ServerConf* unsafe_arena_release_serverconf();

  // @@protoc_insertion_point(class_scope:frp.Config)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frp::LocalConf > localconfs_;
  ::frp::ServerConf* serverconf_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class LocalConf final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:frp.LocalConf) */ {
 public:
  inline LocalConf() : LocalConf(nullptr) {}
  ~LocalConf() override;
  explicit constexpr LocalConf(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LocalConf(const LocalConf& from);
  LocalConf(LocalConf&& from) noexcept
    : LocalConf() {
    *this = ::std::move(from);
  }

  inline LocalConf& operator=(const LocalConf& from) {
    CopyFrom(from);
    return *this;
  }
  inline LocalConf& operator=(LocalConf&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LocalConf& default_instance() {
    return *internal_default_instance();
  }
  static inline const LocalConf* internal_default_instance() {
    return reinterpret_cast<const LocalConf*>(
               &_LocalConf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(LocalConf& a, LocalConf& b) {
    a.Swap(&b);
  }
  inline void Swap(LocalConf* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LocalConf* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LocalConf* New() const final {
    return new LocalConf();
  }

  LocalConf* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LocalConf>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LocalConf& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const LocalConf& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LocalConf* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "frp.LocalConf";
  }
  protected:
  explicit LocalConf(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 2,
    kProtocolFieldNumber = 1,
    kPortFieldNumber = 3,
    kOpenPortFieldNumber = 4,
  };
  // string ip = 2;
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_MUST_USE_RESULT std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // .frp.Protocol protocol = 1;
  void clear_protocol();
  ::frp::Protocol protocol() const;
  void set_protocol(::frp::Protocol value);
  private:
  ::frp::Protocol _internal_protocol() const;
  void _internal_set_protocol(::frp::Protocol value);
  public:

  // uint32 port = 3;
  void clear_port();
  uint32_t port() const;
  void set_port(uint32_t value);
  private:
  uint32_t _internal_port() const;
  void _internal_set_port(uint32_t value);
  public:

  // uint32 openPort = 4;
  void clear_openport();
  uint32_t openport() const;
  void set_openport(uint32_t value);
  private:
  uint32_t _internal_openport() const;
  void _internal_set_openport(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:frp.LocalConf)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
  int protocol_;
  uint32_t port_;
  uint32_t openport_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class ServerConf final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:frp.ServerConf) */ {
 public:
  inline ServerConf() : ServerConf(nullptr) {}
  ~ServerConf() override;
  explicit constexpr ServerConf(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerConf(const ServerConf& from);
  ServerConf(ServerConf&& from) noexcept
    : ServerConf() {
    *this = ::std::move(from);
  }

  inline ServerConf& operator=(const ServerConf& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerConf& operator=(ServerConf&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerConf& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerConf* internal_default_instance() {
    return reinterpret_cast<const ServerConf*>(
               &_ServerConf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(ServerConf& a, ServerConf& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerConf* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerConf* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServerConf* New() const final {
    return new ServerConf();
  }

  ServerConf* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServerConf>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ServerConf& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ServerConf& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerConf* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "frp.ServerConf";
  }
  protected:
  explicit ServerConf(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 1,
    kPortFieldNumber = 2,
  };
  // string ip = 1;
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_MUST_USE_RESULT std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // uint32 port = 2;
  void clear_port();
  uint32_t port() const;
  void set_port(uint32_t value);
  private:
  uint32_t _internal_port() const;
  void _internal_set_port(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:frp.ServerConf)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
  uint32_t port_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Msg

// .frp.MsgType type = 1;
inline void Msg::clear_type() {
  type_ = 0;
}
inline ::frp::MsgType Msg::_internal_type() const {
  return static_cast< ::frp::MsgType >(type_);
}
inline ::frp::MsgType Msg::type() const {
  // @@protoc_insertion_point(field_get:frp.Msg.type)
  return _internal_type();
}
inline void Msg::_internal_set_type(::frp::MsgType value) {
  
  type_ = value;
}
inline void Msg::set_type(::frp::MsgType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:frp.Msg.type)
}

// .frp.LoginReq loginReq = 2;
inline bool Msg::_internal_has_loginreq() const {
  return this != internal_default_instance() && loginreq_ != nullptr;
}
inline bool Msg::has_loginreq() const {
  return _internal_has_loginreq();
}
inline void Msg::clear_loginreq() {
  if (GetArenaForAllocation() == nullptr && loginreq_ != nullptr) {
    delete loginreq_;
  }
  loginreq_ = nullptr;
}
inline const ::frp::LoginReq& Msg::_internal_loginreq() const {
  const ::frp::LoginReq* p = loginreq_;
  return p != nullptr ? *p : reinterpret_cast<const ::frp::LoginReq&>(
      ::frp::_LoginReq_default_instance_);
}
inline const ::frp::LoginReq& Msg::loginreq() const {
  // @@protoc_insertion_point(field_get:frp.Msg.loginReq)
  return _internal_loginreq();
}
inline void Msg::unsafe_arena_set_allocated_loginreq(
    ::frp::LoginReq* loginreq) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(loginreq_);
  }
  loginreq_ = loginreq;
  if (loginreq) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:frp.Msg.loginReq)
}
inline ::frp::LoginReq* Msg::release_loginreq() {
  
  ::frp::LoginReq* temp = loginreq_;
  loginreq_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::frp::LoginReq* Msg::unsafe_arena_release_loginreq() {
  // @@protoc_insertion_point(field_release:frp.Msg.loginReq)
  
  ::frp::LoginReq* temp = loginreq_;
  loginreq_ = nullptr;
  return temp;
}
inline ::frp::LoginReq* Msg::_internal_mutable_loginreq() {
  
  if (loginreq_ == nullptr) {
    auto* p = CreateMaybeMessage<::frp::LoginReq>(GetArenaForAllocation());
    loginreq_ = p;
  }
  return loginreq_;
}
inline ::frp::LoginReq* Msg::mutable_loginreq() {
  ::frp::LoginReq* _msg = _internal_mutable_loginreq();
  // @@protoc_insertion_point(field_mutable:frp.Msg.loginReq)
  return _msg;
}
inline void Msg::set_allocated_loginreq(::frp::LoginReq* loginreq) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete loginreq_;
  }
  if (loginreq) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::frp::LoginReq>::GetOwningArena(loginreq);
    if (message_arena != submessage_arena) {
      loginreq = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, loginreq, submessage_arena);
    }
    
  } else {
    
  }
  loginreq_ = loginreq;
  // @@protoc_insertion_point(field_set_allocated:frp.Msg.loginReq)
}

// .frp.LoginRsp loginRsp = 3;
inline bool Msg::_internal_has_loginrsp() const {
  return this != internal_default_instance() && loginrsp_ != nullptr;
}
inline bool Msg::has_loginrsp() const {
  return _internal_has_loginrsp();
}
inline void Msg::clear_loginrsp() {
  if (GetArenaForAllocation() == nullptr && loginrsp_ != nullptr) {
    delete loginrsp_;
  }
  loginrsp_ = nullptr;
}
inline const ::frp::LoginRsp& Msg::_internal_loginrsp() const {
  const ::frp::LoginRsp* p = loginrsp_;
  return p != nullptr ? *p : reinterpret_cast<const ::frp::LoginRsp&>(
      ::frp::_LoginRsp_default_instance_);
}
inline const ::frp::LoginRsp& Msg::loginrsp() const {
  // @@protoc_insertion_point(field_get:frp.Msg.loginRsp)
  return _internal_loginrsp();
}
inline void Msg::unsafe_arena_set_allocated_loginrsp(
    ::frp::LoginRsp* loginrsp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(loginrsp_);
  }
  loginrsp_ = loginrsp;
  if (loginrsp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:frp.Msg.loginRsp)
}
inline ::frp::LoginRsp* Msg::release_loginrsp() {
  
  ::frp::LoginRsp* temp = loginrsp_;
  loginrsp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::frp::LoginRsp* Msg::unsafe_arena_release_loginrsp() {
  // @@protoc_insertion_point(field_release:frp.Msg.loginRsp)
  
  ::frp::LoginRsp* temp = loginrsp_;
  loginrsp_ = nullptr;
  return temp;
}
inline ::frp::LoginRsp* Msg::_internal_mutable_loginrsp() {
  
  if (loginrsp_ == nullptr) {
    auto* p = CreateMaybeMessage<::frp::LoginRsp>(GetArenaForAllocation());
    loginrsp_ = p;
  }
  return loginrsp_;
}
inline ::frp::LoginRsp* Msg::mutable_loginrsp() {
  ::frp::LoginRsp* _msg = _internal_mutable_loginrsp();
  // @@protoc_insertion_point(field_mutable:frp.Msg.loginRsp)
  return _msg;
}
inline void Msg::set_allocated_loginrsp(::frp::LoginRsp* loginrsp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete loginrsp_;
  }
  if (loginrsp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::frp::LoginRsp>::GetOwningArena(loginrsp);
    if (message_arena != submessage_arena) {
      loginrsp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, loginrsp, submessage_arena);
    }
    
  } else {
    
  }
  loginrsp_ = loginrsp;
  // @@protoc_insertion_point(field_set_allocated:frp.Msg.loginRsp)
}

// .frp.AddConnReq addConnReq = 4;
inline bool Msg::_internal_has_addconnreq() const {
  return this != internal_default_instance() && addconnreq_ != nullptr;
}
inline bool Msg::has_addconnreq() const {
  return _internal_has_addconnreq();
}
inline void Msg::clear_addconnreq() {
  if (GetArenaForAllocation() == nullptr && addconnreq_ != nullptr) {
    delete addconnreq_;
  }
  addconnreq_ = nullptr;
}
inline const ::frp::AddConnReq& Msg::_internal_addconnreq() const {
  const ::frp::AddConnReq* p = addconnreq_;
  return p != nullptr ? *p : reinterpret_cast<const ::frp::AddConnReq&>(
      ::frp::_AddConnReq_default_instance_);
}
inline const ::frp::AddConnReq& Msg::addconnreq() const {
  // @@protoc_insertion_point(field_get:frp.Msg.addConnReq)
  return _internal_addconnreq();
}
inline void Msg::unsafe_arena_set_allocated_addconnreq(
    ::frp::AddConnReq* addconnreq) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(addconnreq_);
  }
  addconnreq_ = addconnreq;
  if (addconnreq) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:frp.Msg.addConnReq)
}
inline ::frp::AddConnReq* Msg::release_addconnreq() {
  
  ::frp::AddConnReq* temp = addconnreq_;
  addconnreq_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::frp::AddConnReq* Msg::unsafe_arena_release_addconnreq() {
  // @@protoc_insertion_point(field_release:frp.Msg.addConnReq)
  
  ::frp::AddConnReq* temp = addconnreq_;
  addconnreq_ = nullptr;
  return temp;
}
inline ::frp::AddConnReq* Msg::_internal_mutable_addconnreq() {
  
  if (addconnreq_ == nullptr) {
    auto* p = CreateMaybeMessage<::frp::AddConnReq>(GetArenaForAllocation());
    addconnreq_ = p;
  }
  return addconnreq_;
}
inline ::frp::AddConnReq* Msg::mutable_addconnreq() {
  ::frp::AddConnReq* _msg = _internal_mutable_addconnreq();
  // @@protoc_insertion_point(field_mutable:frp.Msg.addConnReq)
  return _msg;
}
inline void Msg::set_allocated_addconnreq(::frp::AddConnReq* addconnreq) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete addconnreq_;
  }
  if (addconnreq) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::frp::AddConnReq>::GetOwningArena(addconnreq);
    if (message_arena != submessage_arena) {
      addconnreq = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, addconnreq, submessage_arena);
    }
    
  } else {
    
  }
  addconnreq_ = addconnreq;
  // @@protoc_insertion_point(field_set_allocated:frp.Msg.addConnReq)
}

// .frp.AddConnRsp addConnRsp = 5;
inline bool Msg::_internal_has_addconnrsp() const {
  return this != internal_default_instance() && addconnrsp_ != nullptr;
}
inline bool Msg::has_addconnrsp() const {
  return _internal_has_addconnrsp();
}
inline void Msg::clear_addconnrsp() {
  if (GetArenaForAllocation() == nullptr && addconnrsp_ != nullptr) {
    delete addconnrsp_;
  }
  addconnrsp_ = nullptr;
}
inline const ::frp::AddConnRsp& Msg::_internal_addconnrsp() const {
  const ::frp::AddConnRsp* p = addconnrsp_;
  return p != nullptr ? *p : reinterpret_cast<const ::frp::AddConnRsp&>(
      ::frp::_AddConnRsp_default_instance_);
}
inline const ::frp::AddConnRsp& Msg::addconnrsp() const {
  // @@protoc_insertion_point(field_get:frp.Msg.addConnRsp)
  return _internal_addconnrsp();
}
inline void Msg::unsafe_arena_set_allocated_addconnrsp(
    ::frp::AddConnRsp* addconnrsp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(addconnrsp_);
  }
  addconnrsp_ = addconnrsp;
  if (addconnrsp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:frp.Msg.addConnRsp)
}
inline ::frp::AddConnRsp* Msg::release_addconnrsp() {
  
  ::frp::AddConnRsp* temp = addconnrsp_;
  addconnrsp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::frp::AddConnRsp* Msg::unsafe_arena_release_addconnrsp() {
  // @@protoc_insertion_point(field_release:frp.Msg.addConnRsp)
  
  ::frp::AddConnRsp* temp = addconnrsp_;
  addconnrsp_ = nullptr;
  return temp;
}
inline ::frp::AddConnRsp* Msg::_internal_mutable_addconnrsp() {
  
  if (addconnrsp_ == nullptr) {
    auto* p = CreateMaybeMessage<::frp::AddConnRsp>(GetArenaForAllocation());
    addconnrsp_ = p;
  }
  return addconnrsp_;
}
inline ::frp::AddConnRsp* Msg::mutable_addconnrsp() {
  ::frp::AddConnRsp* _msg = _internal_mutable_addconnrsp();
  // @@protoc_insertion_point(field_mutable:frp.Msg.addConnRsp)
  return _msg;
}
inline void Msg::set_allocated_addconnrsp(::frp::AddConnRsp* addconnrsp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete addconnrsp_;
  }
  if (addconnrsp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::frp::AddConnRsp>::GetOwningArena(addconnrsp);
    if (message_arena != submessage_arena) {
      addconnrsp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, addconnrsp, submessage_arena);
    }
    
  } else {
    
  }
  addconnrsp_ = addconnrsp;
  // @@protoc_insertion_point(field_set_allocated:frp.Msg.addConnRsp)
}

// -------------------------------------------------------------------

// LoginReq

// .frp.LocalConf localConf = 1;
inline bool LoginReq::_internal_has_localconf() const {
  return this != internal_default_instance() && localconf_ != nullptr;
}
inline bool LoginReq::has_localconf() const {
  return _internal_has_localconf();
}
inline void LoginReq::clear_localconf() {
  if (GetArenaForAllocation() == nullptr && localconf_ != nullptr) {
    delete localconf_;
  }
  localconf_ = nullptr;
}
inline const ::frp::LocalConf& LoginReq::_internal_localconf() const {
  const ::frp::LocalConf* p = localconf_;
  return p != nullptr ? *p : reinterpret_cast<const ::frp::LocalConf&>(
      ::frp::_LocalConf_default_instance_);
}
inline const ::frp::LocalConf& LoginReq::localconf() const {
  // @@protoc_insertion_point(field_get:frp.LoginReq.localConf)
  return _internal_localconf();
}
inline void LoginReq::unsafe_arena_set_allocated_localconf(
    ::frp::LocalConf* localconf) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(localconf_);
  }
  localconf_ = localconf;
  if (localconf) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:frp.LoginReq.localConf)
}
inline ::frp::LocalConf* LoginReq::release_localconf() {
  
  ::frp::LocalConf* temp = localconf_;
  localconf_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::frp::LocalConf* LoginReq::unsafe_arena_release_localconf() {
  // @@protoc_insertion_point(field_release:frp.LoginReq.localConf)
  
  ::frp::LocalConf* temp = localconf_;
  localconf_ = nullptr;
  return temp;
}
inline ::frp::LocalConf* LoginReq::_internal_mutable_localconf() {
  
  if (localconf_ == nullptr) {
    auto* p = CreateMaybeMessage<::frp::LocalConf>(GetArenaForAllocation());
    localconf_ = p;
  }
  return localconf_;
}
inline ::frp::LocalConf* LoginReq::mutable_localconf() {
  ::frp::LocalConf* _msg = _internal_mutable_localconf();
  // @@protoc_insertion_point(field_mutable:frp.LoginReq.localConf)
  return _msg;
}
inline void LoginReq::set_allocated_localconf(::frp::LocalConf* localconf) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete localconf_;
  }
  if (localconf) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::frp::LocalConf>::GetOwningArena(localconf);
    if (message_arena != submessage_arena) {
      localconf = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, localconf, submessage_arena);
    }
    
  } else {
    
  }
  localconf_ = localconf;
  // @@protoc_insertion_point(field_set_allocated:frp.LoginReq.localConf)
}

// -------------------------------------------------------------------

// LoginRsp

// int32 ret_code = 1;
inline void LoginRsp::clear_ret_code() {
  ret_code_ = 0;
}
inline int32_t LoginRsp::_internal_ret_code() const {
  return ret_code_;
}
inline int32_t LoginRsp::ret_code() const {
  // @@protoc_insertion_point(field_get:frp.LoginRsp.ret_code)
  return _internal_ret_code();
}
inline void LoginRsp::_internal_set_ret_code(int32_t value) {
  
  ret_code_ = value;
}
inline void LoginRsp::set_ret_code(int32_t value) {
  _internal_set_ret_code(value);
  // @@protoc_insertion_point(field_set:frp.LoginRsp.ret_code)
}

// string err_msg = 2;
inline void LoginRsp::clear_err_msg() {
  err_msg_.ClearToEmpty();
}
inline const std::string& LoginRsp::err_msg() const {
  // @@protoc_insertion_point(field_get:frp.LoginRsp.err_msg)
  return _internal_err_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginRsp::set_err_msg(ArgT0&& arg0, ArgT... args) {
 
 err_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:frp.LoginRsp.err_msg)
}
inline std::string* LoginRsp::mutable_err_msg() {
  std::string* _s = _internal_mutable_err_msg();
  // @@protoc_insertion_point(field_mutable:frp.LoginRsp.err_msg)
  return _s;
}
inline const std::string& LoginRsp::_internal_err_msg() const {
  return err_msg_.Get();
}
inline void LoginRsp::_internal_set_err_msg(const std::string& value) {
  
  err_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* LoginRsp::_internal_mutable_err_msg() {
  
  return err_msg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* LoginRsp::release_err_msg() {
  // @@protoc_insertion_point(field_release:frp.LoginRsp.err_msg)
  return err_msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void LoginRsp::set_allocated_err_msg(std::string* err_msg) {
  if (err_msg != nullptr) {
    
  } else {
    
  }
  err_msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), err_msg,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (err_msg_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    err_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:frp.LoginRsp.err_msg)
}

// string client_id = 3;
inline void LoginRsp::clear_client_id() {
  client_id_.ClearToEmpty();
}
inline const std::string& LoginRsp::client_id() const {
  // @@protoc_insertion_point(field_get:frp.LoginRsp.client_id)
  return _internal_client_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginRsp::set_client_id(ArgT0&& arg0, ArgT... args) {
 
 client_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:frp.LoginRsp.client_id)
}
inline std::string* LoginRsp::mutable_client_id() {
  std::string* _s = _internal_mutable_client_id();
  // @@protoc_insertion_point(field_mutable:frp.LoginRsp.client_id)
  return _s;
}
inline const std::string& LoginRsp::_internal_client_id() const {
  return client_id_.Get();
}
inline void LoginRsp::_internal_set_client_id(const std::string& value) {
  
  client_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* LoginRsp::_internal_mutable_client_id() {
  
  return client_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* LoginRsp::release_client_id() {
  // @@protoc_insertion_point(field_release:frp.LoginRsp.client_id)
  return client_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void LoginRsp::set_allocated_client_id(std::string* client_id) {
  if (client_id != nullptr) {
    
  } else {
    
  }
  client_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), client_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (client_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    client_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:frp.LoginRsp.client_id)
}

// -------------------------------------------------------------------

// AddConnReq

// string conn_id = 1;
inline void AddConnReq::clear_conn_id() {
  conn_id_.ClearToEmpty();
}
inline const std::string& AddConnReq::conn_id() const {
  // @@protoc_insertion_point(field_get:frp.AddConnReq.conn_id)
  return _internal_conn_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddConnReq::set_conn_id(ArgT0&& arg0, ArgT... args) {
 
 conn_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:frp.AddConnReq.conn_id)
}
inline std::string* AddConnReq::mutable_conn_id() {
  std::string* _s = _internal_mutable_conn_id();
  // @@protoc_insertion_point(field_mutable:frp.AddConnReq.conn_id)
  return _s;
}
inline const std::string& AddConnReq::_internal_conn_id() const {
  return conn_id_.Get();
}
inline void AddConnReq::_internal_set_conn_id(const std::string& value) {
  
  conn_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AddConnReq::_internal_mutable_conn_id() {
  
  return conn_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AddConnReq::release_conn_id() {
  // @@protoc_insertion_point(field_release:frp.AddConnReq.conn_id)
  return conn_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AddConnReq::set_allocated_conn_id(std::string* conn_id) {
  if (conn_id != nullptr) {
    
  } else {
    
  }
  conn_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), conn_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (conn_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    conn_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:frp.AddConnReq.conn_id)
}

// -------------------------------------------------------------------

// AddConnRsp

// int32 ret_code = 1;
inline void AddConnRsp::clear_ret_code() {
  ret_code_ = 0;
}
inline int32_t AddConnRsp::_internal_ret_code() const {
  return ret_code_;
}
inline int32_t AddConnRsp::ret_code() const {
  // @@protoc_insertion_point(field_get:frp.AddConnRsp.ret_code)
  return _internal_ret_code();
}
inline void AddConnRsp::_internal_set_ret_code(int32_t value) {
  
  ret_code_ = value;
}
inline void AddConnRsp::set_ret_code(int32_t value) {
  _internal_set_ret_code(value);
  // @@protoc_insertion_point(field_set:frp.AddConnRsp.ret_code)
}

// string err_msg = 2;
inline void AddConnRsp::clear_err_msg() {
  err_msg_.ClearToEmpty();
}
inline const std::string& AddConnRsp::err_msg() const {
  // @@protoc_insertion_point(field_get:frp.AddConnRsp.err_msg)
  return _internal_err_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddConnRsp::set_err_msg(ArgT0&& arg0, ArgT... args) {
 
 err_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:frp.AddConnRsp.err_msg)
}
inline std::string* AddConnRsp::mutable_err_msg() {
  std::string* _s = _internal_mutable_err_msg();
  // @@protoc_insertion_point(field_mutable:frp.AddConnRsp.err_msg)
  return _s;
}
inline const std::string& AddConnRsp::_internal_err_msg() const {
  return err_msg_.Get();
}
inline void AddConnRsp::_internal_set_err_msg(const std::string& value) {
  
  err_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AddConnRsp::_internal_mutable_err_msg() {
  
  return err_msg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AddConnRsp::release_err_msg() {
  // @@protoc_insertion_point(field_release:frp.AddConnRsp.err_msg)
  return err_msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AddConnRsp::set_allocated_err_msg(std::string* err_msg) {
  if (err_msg != nullptr) {
    
  } else {
    
  }
  err_msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), err_msg,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (err_msg_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    err_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:frp.AddConnRsp.err_msg)
}

// string conn_id = 3;
inline void AddConnRsp::clear_conn_id() {
  conn_id_.ClearToEmpty();
}
inline const std::string& AddConnRsp::conn_id() const {
  // @@protoc_insertion_point(field_get:frp.AddConnRsp.conn_id)
  return _internal_conn_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddConnRsp::set_conn_id(ArgT0&& arg0, ArgT... args) {
 
 conn_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:frp.AddConnRsp.conn_id)
}
inline std::string* AddConnRsp::mutable_conn_id() {
  std::string* _s = _internal_mutable_conn_id();
  // @@protoc_insertion_point(field_mutable:frp.AddConnRsp.conn_id)
  return _s;
}
inline const std::string& AddConnRsp::_internal_conn_id() const {
  return conn_id_.Get();
}
inline void AddConnRsp::_internal_set_conn_id(const std::string& value) {
  
  conn_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AddConnRsp::_internal_mutable_conn_id() {
  
  return conn_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AddConnRsp::release_conn_id() {
  // @@protoc_insertion_point(field_release:frp.AddConnRsp.conn_id)
  return conn_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AddConnRsp::set_allocated_conn_id(std::string* conn_id) {
  if (conn_id != nullptr) {
    
  } else {
    
  }
  conn_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), conn_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (conn_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    conn_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:frp.AddConnRsp.conn_id)
}

// -------------------------------------------------------------------

// Config

// .frp.ServerConf serverConf = 1;
inline bool Config::_internal_has_serverconf() const {
  return this != internal_default_instance() && serverconf_ != nullptr;
}
inline bool Config::has_serverconf() const {
  return _internal_has_serverconf();
}
inline void Config::clear_serverconf() {
  if (GetArenaForAllocation() == nullptr && serverconf_ != nullptr) {
    delete serverconf_;
  }
  serverconf_ = nullptr;
}
inline const ::frp::ServerConf& Config::_internal_serverconf() const {
  const ::frp::ServerConf* p = serverconf_;
  return p != nullptr ? *p : reinterpret_cast<const ::frp::ServerConf&>(
      ::frp::_ServerConf_default_instance_);
}
inline const ::frp::ServerConf& Config::serverconf() const {
  // @@protoc_insertion_point(field_get:frp.Config.serverConf)
  return _internal_serverconf();
}
inline void Config::unsafe_arena_set_allocated_serverconf(
    ::frp::ServerConf* serverconf) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(serverconf_);
  }
  serverconf_ = serverconf;
  if (serverconf) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:frp.Config.serverConf)
}
inline ::frp::ServerConf* Config::release_serverconf() {
  
  ::frp::ServerConf* temp = serverconf_;
  serverconf_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::frp::ServerConf* Config::unsafe_arena_release_serverconf() {
  // @@protoc_insertion_point(field_release:frp.Config.serverConf)
  
  ::frp::ServerConf* temp = serverconf_;
  serverconf_ = nullptr;
  return temp;
}
inline ::frp::ServerConf* Config::_internal_mutable_serverconf() {
  
  if (serverconf_ == nullptr) {
    auto* p = CreateMaybeMessage<::frp::ServerConf>(GetArenaForAllocation());
    serverconf_ = p;
  }
  return serverconf_;
}
inline ::frp::ServerConf* Config::mutable_serverconf() {
  ::frp::ServerConf* _msg = _internal_mutable_serverconf();
  // @@protoc_insertion_point(field_mutable:frp.Config.serverConf)
  return _msg;
}
inline void Config::set_allocated_serverconf(::frp::ServerConf* serverconf) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete serverconf_;
  }
  if (serverconf) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::frp::ServerConf>::GetOwningArena(serverconf);
    if (message_arena != submessage_arena) {
      serverconf = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, serverconf, submessage_arena);
    }
    
  } else {
    
  }
  serverconf_ = serverconf;
  // @@protoc_insertion_point(field_set_allocated:frp.Config.serverConf)
}

// repeated .frp.LocalConf localConfs = 2;
inline int Config::_internal_localconfs_size() const {
  return localconfs_.size();
}
inline int Config::localconfs_size() const {
  return _internal_localconfs_size();
}
inline void Config::clear_localconfs() {
  localconfs_.Clear();
}
inline ::frp::LocalConf* Config::mutable_localconfs(int index) {
  // @@protoc_insertion_point(field_mutable:frp.Config.localConfs)
  return localconfs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frp::LocalConf >*
Config::mutable_localconfs() {
  // @@protoc_insertion_point(field_mutable_list:frp.Config.localConfs)
  return &localconfs_;
}
inline const ::frp::LocalConf& Config::_internal_localconfs(int index) const {
  return localconfs_.Get(index);
}
inline const ::frp::LocalConf& Config::localconfs(int index) const {
  // @@protoc_insertion_point(field_get:frp.Config.localConfs)
  return _internal_localconfs(index);
}
inline ::frp::LocalConf* Config::_internal_add_localconfs() {
  return localconfs_.Add();
}
inline ::frp::LocalConf* Config::add_localconfs() {
  ::frp::LocalConf* _add = _internal_add_localconfs();
  // @@protoc_insertion_point(field_add:frp.Config.localConfs)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frp::LocalConf >&
Config::localconfs() const {
  // @@protoc_insertion_point(field_list:frp.Config.localConfs)
  return localconfs_;
}

// -------------------------------------------------------------------

// LocalConf

// .frp.Protocol protocol = 1;
inline void LocalConf::clear_protocol() {
  protocol_ = 0;
}
inline ::frp::Protocol LocalConf::_internal_protocol() const {
  return static_cast< ::frp::Protocol >(protocol_);
}
inline ::frp::Protocol LocalConf::protocol() const {
  // @@protoc_insertion_point(field_get:frp.LocalConf.protocol)
  return _internal_protocol();
}
inline void LocalConf::_internal_set_protocol(::frp::Protocol value) {
  
  protocol_ = value;
}
inline void LocalConf::set_protocol(::frp::Protocol value) {
  _internal_set_protocol(value);
  // @@protoc_insertion_point(field_set:frp.LocalConf.protocol)
}

// string ip = 2;
inline void LocalConf::clear_ip() {
  ip_.ClearToEmpty();
}
inline const std::string& LocalConf::ip() const {
  // @@protoc_insertion_point(field_get:frp.LocalConf.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LocalConf::set_ip(ArgT0&& arg0, ArgT... args) {
 
 ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:frp.LocalConf.ip)
}
inline std::string* LocalConf::mutable_ip() {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:frp.LocalConf.ip)
  return _s;
}
inline const std::string& LocalConf::_internal_ip() const {
  return ip_.Get();
}
inline void LocalConf::_internal_set_ip(const std::string& value) {
  
  ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* LocalConf::_internal_mutable_ip() {
  
  return ip_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* LocalConf::release_ip() {
  // @@protoc_insertion_point(field_release:frp.LocalConf.ip)
  return ip_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void LocalConf::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    
  } else {
    
  }
  ip_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ip,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (ip_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    ip_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:frp.LocalConf.ip)
}

// uint32 port = 3;
inline void LocalConf::clear_port() {
  port_ = 0u;
}
inline uint32_t LocalConf::_internal_port() const {
  return port_;
}
inline uint32_t LocalConf::port() const {
  // @@protoc_insertion_point(field_get:frp.LocalConf.port)
  return _internal_port();
}
inline void LocalConf::_internal_set_port(uint32_t value) {
  
  port_ = value;
}
inline void LocalConf::set_port(uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:frp.LocalConf.port)
}

// uint32 openPort = 4;
inline void LocalConf::clear_openport() {
  openport_ = 0u;
}
inline uint32_t LocalConf::_internal_openport() const {
  return openport_;
}
inline uint32_t LocalConf::openport() const {
  // @@protoc_insertion_point(field_get:frp.LocalConf.openPort)
  return _internal_openport();
}
inline void LocalConf::_internal_set_openport(uint32_t value) {
  
  openport_ = value;
}
inline void LocalConf::set_openport(uint32_t value) {
  _internal_set_openport(value);
  // @@protoc_insertion_point(field_set:frp.LocalConf.openPort)
}

// -------------------------------------------------------------------

// ServerConf

// string ip = 1;
inline void ServerConf::clear_ip() {
  ip_.ClearToEmpty();
}
inline const std::string& ServerConf::ip() const {
  // @@protoc_insertion_point(field_get:frp.ServerConf.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServerConf::set_ip(ArgT0&& arg0, ArgT... args) {
 
 ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:frp.ServerConf.ip)
}
inline std::string* ServerConf::mutable_ip() {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:frp.ServerConf.ip)
  return _s;
}
inline const std::string& ServerConf::_internal_ip() const {
  return ip_.Get();
}
inline void ServerConf::_internal_set_ip(const std::string& value) {
  
  ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ServerConf::_internal_mutable_ip() {
  
  return ip_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ServerConf::release_ip() {
  // @@protoc_insertion_point(field_release:frp.ServerConf.ip)
  return ip_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ServerConf::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    
  } else {
    
  }
  ip_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ip,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (ip_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    ip_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:frp.ServerConf.ip)
}

// uint32 port = 2;
inline void ServerConf::clear_port() {
  port_ = 0u;
}
inline uint32_t ServerConf::_internal_port() const {
  return port_;
}
inline uint32_t ServerConf::port() const {
  // @@protoc_insertion_point(field_get:frp.ServerConf.port)
  return _internal_port();
}
inline void ServerConf::_internal_set_port(uint32_t value) {
  
  port_ = value;
}
inline void ServerConf::set_port(uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:frp.ServerConf.port)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace frp

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::frp::MsgType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::frp::MsgType>() {
  return ::frp::MsgType_descriptor();
}
template <> struct is_proto_enum< ::frp::Protocol> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::frp::Protocol>() {
  return ::frp::Protocol_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
